project:
  type: website
  output-dir: docs

website:
  title: "📚 GitHub + R Lab Tutorial"
  repo-url: https://github.com/blamp23/github-r-lab-tutorial
  repo-actions: [edit, issue]

  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
