name: Deploy Quarto site

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      # 1 – Check out your repo
      - uses: actions/checkout@v4

      # 2 – Install the latest R (needed for .qmd files that use R)
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      # 3 – Install Quarto CLI
      - uses: quarto-dev/quarto-actions/setup@v2

      # 4 – Render the website into the default _site/ directory
      - name: Render site
        run: quarto render

      # 5 – Configure GitHub Pages
      - uses: actions/configure-pages@v5

      # 6 – Upload the rendered site as an artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      # 7 – Deploy the artifact to GitHub Pages
      - uses: actions/deploy-pages@v4
        id: deploy

