name: Deploy Quarto site

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: quarto render

      - uses: actions/configure-pages@v5       # ← new
      - uses: actions/upload-pages-artifact@v3 # ← new
        with:
          path: _site
      - uses: actions/deploy-pages@v4          # ← new
        id: deploy

